---
resources:
- name: bosh-hub
  type: git
  source:
    uri: https://github.com/cppforlife/bosh-hub
    branch: master
- name: cf-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
- name: releases-index
  type: git
  source:
    uri: https://github.com/bosh-io/releases-index
    branch: master
- name: stemcells-legacy-index
  type: git
  source:
    uri: https://github.com/bosh-io/stemcells-legacy-index
    branch: master
- name: stemcells-core-index
  type: git
  source:
    uri: https://github.com/bosh-io/stemcells-core-index
    branch: master
- name: stemcells-cpi-index
  type: git
  source:
    uri: https://github.com/bosh-io/stemcells-cpi-index
    branch: master
- name: stemcells-softlayer-index
  type: git
  source:
    uri: https://github.com/bosh-io/stemcells-softlayer-index
    branch: master
- name: stemcells-windows-index
  type: git
  source:
    uri: https://github.com/bosh-io/stemcells-windows-index
    branch: master
- name: 1h
  type: time
  source:
    interval: 1h

jobs:
- name: pull-data
  serial: true
  plan:
  - aggregate:
    - get: releases-index
      trigger: true
    - get: stemcells-legacy-index
      trigger: true
    - get: stemcells-core-index
      trigger: true
    - get: stemcells-cpi-index
      trigger: true
    - get: stemcells-softlayer-index
      trigger: true
    - get: stemcells-windows-index
      trigger: true
    - get: 1h
      trigger: true
    - get: cf-cli
      version:
        ref: e2adc618bba80455c0820ea8099cc68c53438b98
    - get: bosh-hub
  - task: pull-data
    params:
      CF_USERNAME: ((cf_username))
      CF_PASSWORD: ((cf_password))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: "golang"
          tag: "1.8.3"
      inputs:
      - name: bosh-hub
      - name: cf-cli
        path: src/code.cloudfoundry.org/cli
      run:
        path: bash
        args:
        - -c
        - |
          set -eu
          dir=$PWD
          export GOPATH=$dir
          cd src/code.cloudfoundry.org/cli
          make build || true # ignore some git problem
          export PATH=$PWD/out:$PATH
          cf api https://api.run.pivotal.io
          cf auth "$CF_USERNAME" "$CF_PASSWORD"
          cf target -o cfcommunity -s boshorg
          exec $dir/bosh-hub/pull-data.sh
