---
resources:
- name: release
  type: git
  check_every: 5m
  source:
    uri: ((release_git_url))

- name: releases-index
  type: git
  source:
    uri: ((releases_index_git_url))
    branch: master
    private_key: ((releases_index_private_key))

- name: worker
  type: git
  source:
    uri: https://github.com/bosh-io/worker.git

jobs:
- name: create-release
  serial: true
  plan:
  - aggregate:
    - get: worker
    - get: release
      trigger: true
      params:
        submodules: none
    - get: releases-index
  - task: create-release
    params:
      AWS_ACCESS_KEY_ID: ((s3_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((s3_secret_access_key))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: "golang"
          tag: "1.8.3"
      inputs:
      - name: release
      - name: releases-index
        path: releases-index-input
      - name: worker
      outputs:
      - name: releases-index
      run:
        path: bash
        args:
        - -c
        - |
          set -eu
          wget -O /usr/bin/bosh https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.28-linux-amd64
          echo "7b7629fcdf8839cf29bf25d97e8ea6beb3b9a7b2  /usr/bin/bosh" | shasum -c -
          chmod +x /usr/bin/bosh
          wget -O /usr/bin/meta4 https://s3.amazonaws.com/dk-shared-assets/meta4-0.1.0-linux-amd64
          echo "235bc60706793977446529830c2cb319e6aaf2da  /usr/bin/meta4" | shasum -c -
          chmod +x /usr/bin/meta4
          taskdir=$PWD
          git clone releases-index-input releases-index
          export GOPATH=$taskdir/worker
          cd $GOPATH/src/worker
          go run create-releases.go "$taskdir/release" "$taskdir/releases-index/((release_repo))" "((release_min_version))" "((s3_endpoint))"
    ensure:
      put: releases-index
      params:
        repository: releases-index
        rebase: true
